### ISSUE TITLE
Doesn't work with multiple hosts

### ISSUE THREAD

**Issue by dalehenries** [geospin-takelage/takelage-var#1]
I'd like to start by saying I love this project.  It makes testing molecule roles much cleaner and more readable.

The issue I'm having, is that this doesn't work if you have more than one host in your inventory.  The testvars object always has the variables of the first inventory host.

To test, create a new role and set your molecule.yml as follows:
```yml
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-1
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: instance-2
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      instance-1:
        example_var: no
      instance-2:
        example_var: yes
verifier:
  name: testinfra
  options:
    s: true
    testvars-no-gather-facts: true
```

Here's the test_default.py:

```python
import takeltest

testinfra_hosts = takeltest.hosts()

def test_hostname(host, testvars):
    cmd = host.run("hostname")
    example_var = testvars['example_var']
    print("\nhostname:" + cmd.stdout + "example_var: " + str(example_var))

```

Output:
```
    tests/test_default.py
    hostname:instance-1
     example_var: False
    .
    hostname:instance-2
     example_var: False
    .
```

As you can see, example_var should be `True` for instance-2, but it's getting the variables of instance-1.

**Comment by runlevel-six** [comment]
I'm running into this as well on a 5 node build. I'm having to use less-ideal methods for pulling in vars (reading in files instead of pulling them from Ansible) to move forward with tests.

**Comment by stephan-devop** [comment]
You are absolutely right and we've came across this shortcoming at my company as well. (Our workaround at the moment is: use only one host per scenario and start the other hosts in prepare/side_effect playbooks.)

There are two separate issues here:

_(1) The first host is used._

This is due to `AnsibleHost` in [ansibleres.py](https://github.com/geospin-takelage/takelage-var/blob/master/takeltest/ansibleres.py).

_(2) The variables are only resolved for one host._

That is the case because the fixtures have `session` scope (defined in [plugins.py](https://github.com/geospin-takelage/takelage-var/blob/master/takeltest/plugin.py)).

While we have already discussed different more or less easy solutions for (1) I am not aware of a solution for (2). Even if there was it probably came with a severe execution time penalty.

Do you have any suggestions?

**Comment by stephan-devop** [comment]
Let's do some brainstorming. First, have a look at [plugins.py](https://github.com/geospin-takelage/takelage-var/blob/master/takeltest/plugin.py):

At the moment `testvars` gets a `moleculebook` which gets a `moleculeplay` which gets an `ansiblehost`. If we want the variables of multiple hosts, we'd need multiple of these fixture chains. Or better: one chain which passes on multiple hosts.

But then `testvars` would return a (hosts) dictionary of (variables) dictionaries which would spoil the easy use of `testvars` in the most likely case of a single host. This could be solved by introducing a new kind of fixture with a different name which would do exactly this. Let's call it `multitestvars`. Then `testvars` could return `multitestvars[next(iter(multitestvars.values))]` and nothing would change for existing tests.

So `ansiblehost` has to become `ansiblehosts` and `moleculeplay` has to become `moleculeplays` and `moleculebook` has to become `moleculebooks`. Then we could loop over the `moleculebooks` in [testvars.py](https://github.com/geospin-takelage/takelage-var/blob/master/takeltest/testvars.py) (which becomes `multitestvars.py`) and return the desired dictionary of variables.

Then we could access varibles like so:
`multivars['my_third_node']['my_var']`

What do you think about this idea?

**Comment by dalehenries** [comment]
While digging through this, I noticed that testinfra has a host.ansible.get_variables() function:
https://testinfra.readthedocs.io/en/latest/modules.html#testinfra.modules.ansible.Ansible.get_variables

From what I understand, it looks like your solution would work, but I think we can just use:

```python
def test_hostname(host):
    cmd = host.run("hostname")
    testvars = host.ansible.get_variables()
    example_var = testvars['example_var']
    print("\nhostname:" + cmd.stdout + "example_var: " + str(example_var))
```
To be honest, I doubt I'm understanding all of the use cases here, but this seems to work for my situation.

**Comment by stephan-devop** [comment]
Unfortunately not. That function does not return role variables and it does not resolve variables.

**Comment by dalehenries** [comment]
I see what you mean by role variables, but what do you mean that it doesn't resolve variables?  It seems like it just pulls values from the inventory section of the molecule.yml file.

**Comment by alex-devop** [comment]
> but what do you mean that it doesn't resolve variables? It seems like it just pulls values from the inventory section of the molecule.yml file

The idea is, that takelage-var should recursive resolve variables. For example if you have the fowllowing variables in a role or in group_vars 

bar_one: 'A string'
bar_two: 42
foo_dict:
  - "{{ bar_one }}"
  - "{{ bar_two }}"

takelage-var should return the resolved foo_dict

foo_dict:
  - 'A string'
  - 42

**Comment by dalehenries** [comment]
> > but what do you mean that it doesn't resolve variables? It seems like it just pulls values from the inventory section of the molecule.yml file
> 
> The idea is, that takelage-var should recursive resolve variables. For example if you have the fowllowing variables in a role or in group_vars
> 
> bar_one: 'A string'
> bar_two: 42
> foo_dict:
> 
> * "{{ bar_one }}"
> * "{{ bar_two }}"
> 
> takelage-var should return the resolved foo_dict
> 
> foo_dict:
> 
> * 'A string'
> * 42

Thanks for the clarification

**Comment by stephan-devop** [comment]
There are a couple of other advantages. Most importantly, `testvars` uses ansible's `VariableManager` so it inherits its precedence rules. You probably won't this unless you overwrite role variables or variables in the `all` group (and thus are using links e.g. to `group_vars` instead of defining the variables in your `molecule.yml`)

**Comment by stephan-devop** [comment]
This feature has been implemented, see [multi](https://github.com/geospin-takelage/takelage-var/tree/master/test/system/multi) system test.

`molecule.yml`:

```yaml
...
platforms:
  - name: molecule-takeltest-multi-first
    image: takelage/takelbase
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    groups:
      - private
  - name: molecule-takeltest-multi-second
    image: takelage/takelbase
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    groups:
      - private
...
```

`test_default.py`:

```python
...
def test_takeltest_multi_hostname(multitestvars, testvars):
    assert not multitestvars['molecule-takeltest-multi-first']['example_var']
    assert multitestvars['molecule-takeltest-multi-second']['example_var']
    assert testvars['ansible_facts']['hostname'] == \
           'molecule-takeltest-multi-first'
```
